# Generated by Django 5.1.3 on 2024-11-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_cliente_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidade_maxima',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='produto',
            name='quantidade_minima',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
